### ISSUE TITLE
Replace `null` with undefined/void

### ISSUE THREAD

**Issue by fregante** [cheap-glitch/mi-cron#1]
https://github.com/sindresorhus/meta/issues/7

Thoughts?

**Comment by cheap-glitch** [comment]
I haven't got any strong opinions about this, so I'm okay to change it to `undefined`.

Plus since this was primarily made to be used by Refined GitHub, it makes sense to change it to whatever you think would be more convenient.

**Comment by cheap-glitch** [comment]
I'll hold off on releasing this for a few days. I documented the API in the readme, if you want any changes just ask.

**Comment by notlmn** [comment]
I was about to ask for chaining `nextDate()`, but I see that it is already available in other way https://github.com/cheap-glitch/mi-cron/commit/bb3d8e625c394026725af434a8347f917dac3c90.

Awesome work @cheap-glitch 🎉
